# Retail Inventory Demand Forecasting
## Introduction

This project focuses on analyzing and forecasting retail store inventory and product demand using historical sales data. The goal is to develop predictive models that accurately estimate future demand, which can significantly enhance:

- Inventory management
- Reduction of stockouts and overstocking
- Operational efficiency across retail networks

# Table of Contents

| S.No | Project Topic                         | Description                                                                                          |
|------|--------------------------------------|------------------------------------------------------------------------------------------------------|
| 1    | [Project Objectives](#1.Project-Objectives) | Define the main goals and objectives of the project.                                                 |
| 2    | [Describe the Dataset](#2.Describe-the-Dataset) | Review the [dataset](https://www.kaggle.com/datasets/atomicd/retail-store-inventory-and-demand-forecasting) from Kaggle.com. |
| 3    | [Data Cleaning and Preparation](#3.Data-Cleaning-And-Preparation) | Prepare and clean the dataset for further analysis and modeling.                                     |
| 4    | [Data Analysis](#4.Data-Analysis)      | Perform statistical analysis and visualization on the dataset.                                       |
| 5    | [Model Selection](#5.Model-Selection)  | Select appropriate machine learning models for the project.                                          |
| 6    | [Model Analysis and Prediction](#6.Model-Analysis-And-Prediction) | Train and test the selected model(s) and evaluate performance.                                       |
| 7    | [Conclusion](#7.Conclusion)            | Summarize the findings and insights from the project.                                                |
| 8    | [Appendix](#8.Appendix)                | Include supplementary material, such as code snippets or additional details.                         |
| 9    | [Contributions](#9.Contributions)      | List the contributors to the project.                                                                |


---

## 1.Project Objectives

This project focuses on analyzing and forecasting retail store inventory and product demand using historical sales data. The dataset includes transaction-level records of various items across multiple stores. The main objective is to build predictive models that accurately forecast future demand, enabling better inventory management, reducing stockouts and overstocking, and ultimately improving operational efficiency

## 2.Describe the Dataset

In this section, we will explore the dataset and provide a detailed description of its structure, features, and contents. For this project, we have used a dataset from Kaggle: **[Retail Store Inventory and Demand Forecasting](https://www.kaggle.com/datasets/atomicd/retail-store-inventory-and-demand-forecasting)**. The dataset has been downloaded and stored in this project repository [**sales_data**](./dataset/sales_data.csv)

### 2.1 Load the dataset

In [112]:
import pandas as pd
sales_df = pd.read_csv('./dataset/sales_data.csv')
sales_df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

### 2.2 studying the dataset

The dataset includes 76,000 records with both categorical and numerical features, essential for understanding demand patterns and forecasting. Below is a description of each variable:

In [130]:
sales_df.describe()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand
count,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000
mean,301.062842,88.827316,89.090645,67.726028,9.087039,0.328947,69.454029,0.200000,104.317158
std,226.510161,43.994525,162.404627,39.377899,7.475781,0.469834,40.943818,0.400003,46.964801
min,0.000000,0.000000,0.000000,4.740000,0.000000,0.000000,4.290000,0.000000,4.000000
25%,136.000000,58.000000,0.000000,31.997500,5.000000,0.000000,32.620000,0.000000,71.000000
50%,227.000000,84.000000,0.000000,64.500000,10.000000,0.000000,65.700000,0.000000,100.000000
75%,408.000000,114.000000,121.000000,95.830000,10.000000,1.000000,97.932500,0.000000,133.000000
max,2267.000000,426.000000,1616.000000,228.030000,25.000000,1.000000,261.220000,1.000000,430.000000

## 3.Data Cleaning and Preparation

In this section, we will load the dataset, examine its structure, and perform any necessary cleaning or adjustments to ensure the data is suitable for analysis.

From the `sales_df.describe()` output we observer the categorical features like Store ID, Product ID, Category, Region, Weather Condition, etc were removed. This is because pandas library will only process numberic features. So handle the categorical data we should encode the data.

### 3.1 Handle missing data
### 3.2 Drop irrelevant columns. 
### 3.3 Encoding the Categorical features.

## 4.Data Analysis
Perform statistical analysis on the dataset.

## 5.Model Selection
Choose a suitable machine learning model for the project.

## 6.Model Analysis And Prediction

## 7.Conclusion

## 8.Appendix

## 9.Contributions
- [Jagdish Mane](https://www.linkedin.com/in/jagdish-mane/)
- [Sachine Shukla](https://www.linkedin.com/in/sks336/)
- [Hanmant Kattimani](https://www.linkedin.com/in/hanmant-kattimani-b8323741/)